version: "3"
name: "lfroauth"
services:
  liferay:
    hostname: portal.dev.local
    container_name: lfroauth-liferay
    build:
      dockerfile: liferay/liferay.Dockerfile
      context: .
    ports:
      - "80:8080"
    env_file:
      - ./liferay/variables.env
    volumes:
      - liferay_data:/opt/liferay/data
      - ./liferay/files:/mnt/liferay/files
      - ./liferay/deploy:/opt/liferay/deploy
    depends_on:
      - db
      - sso
    entrypoint: /usr/local/bin/wait-for -t 60 db:3306 -- /usr/local/bin/liferay_entrypoint.sh
  db:
    container_name: lfroauth-db
    build:
      dockerfile: mysql/mysql.Dockerfile
      context: .
    env_file:
      - ./mysql/variables.env
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
  mail:
    hostname: mail.dev.local
    container_name: lfroauth-mail
    build:
      dockerfile: smtp4dev/smtp4dev.Dockerfile
      context: .
    ports:
      - "5000:80"
    volumes:
      - smtp_data:/smtp4dev
  sso:
    build:
      dockerfile: keycloak/keycloak.Dockerfile
      context: .
    hostname: sso.dev.local
    container_name: lfroauth-sso
    ports:
      - "8080:8080"
    env_file:
      - ./keycloak/variables.env
    volumes:
      - ./keycloak/liferay-realm.json:/opt/keycloak/data/import/liferay-realm.json
    depends_on:
      - db
    command:
      - start-dev
      - --import-realm

  apim:
    hostname: apim.dev.local
    container_name: lfroauth-apim
    build:
      dockerfile: kong/kong.Dockerfile
      context: .
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://apim.dev.local:8002
      KONG_PLUGINS: bundled,oauth-liferay-introspect
    ports: 
      - 8800:8000
      - 8443:8443
      - 8001:8001  
      - 8444:8444
      - 8002:8002  
      - 8445:8445  
      - 8003:8003  
      - 8004:8004
    volumes:
      - ./kong/declarative:/kong/declarative/
      - ./kong/plugins:/kong/plugins/

  app1:
    hostname: app1.dev.local
    container_name: lfroauth-app1
    build:
      context: ./front-end
      dockerfile: ./app1.Dockerfile
      args: 
        - TITLE=react-app
    ports:
      - 3007:80
      - 3008:443  # HTTPS
    volumes:
      - ./front-end/react-app:/app/react-app
      - /home/user1/node_modules:/app/react-app/node_modules
      - ./certs/app1.dev.local:/etc/nginx/ssl  # Montage des certificats
    depends_on:
      - mkcert

  mkcert:
    image: fuzzy/mkcert
    container_name: mkcert
    command: >
      sh -c "
      mkcert -install &&
      mkcert -cert-file /certs/app1.dev.local.crt -key-file /certs/app1.dev.local.key app1.dev.local localhost 127.0.0.1 ::1"
    volumes:
      - ./certs:/certs
    entrypoint: /bin/sh

volumes:
  liferay_data:
  smtp_data:
  db_data:
